### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 4.53 GiB already allocated; 7.14 MiB free; 45.53 MiB cached)

### ISSUE THREAD

**Issue by Shanzaay** [tshi04/AbsSum#10]
I am working on bytecup dataset. When i try to train it using main.py file. I get the error on model.py at line 56:
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 4.53 GiB already allocated; 7.14 MiB free; 45.53 MiB cached)

Is there any general way to resolve it?

**Comment by Shanzaay** [comment]
How much memory does it need to train anyway?

**Comment by tshi04** [comment]
For training pointer-generator networks it may take 8GB+, I used to use P100 (16GB), Tesla XP (12GB) to train.

**Comment by Shanzaay** [comment]
The model.py file has different models in it. So am I suppose to use one of
them or what. I am a bit confused.

**Comment by tshi04** [comment]
check main.py for all options.
