### ISSUE TITLE
Is pretrained weights available for the models ?

### ISSUE THREAD

**Issue by ykumargupta** [tshi04/AbsSum#13]
It would be very helpful if pretrained weights are provided for the several models . Thank you

**Comment by tshi04** [comment]
https://drive.google.com/file/d/1KEYj5OtNIe4XkO_NxDzs808QC9zkznIm/view?usp=sharing

**Comment by tshi04** [comment]
I don't have the pre-trained weights. The results were usually stable (< 1 rouge-1).
