### ISSUE TITLE
ModuleNotFoundError: No module named 'newsroom'

### ISSUE THREAD

**Issue by Shanzaay** [tshi04/AbsSum#7]
Hi. I am getting this module error. am I suppose to download it somewhere or do I need a newsroom.py file or something? Because I can't seem to find any file in the code. What am I missing?

**Comment by tshi04** [comment]
Can you give me more details? I did not follow your question.

**Comment by Shanzaay** [comment]
sorry for the late response. The problem is solved now. Thanks anyway.
