### ISSUE TITLE
Code execute guidance 

### ISSUE THREAD

**Issue by Shanzaay** [tshi04/AbsSum#8]
Hi. Can you give a step by step instruction on how to execute this code?  I am having a hard time figuring that out. Please

**Comment by Shanzaay** [comment]
I have a newsroom dataset with files name as test-stats.jsonl. so the first step I did is to use  extract_corenlp.py . but when I run the file with newsroom dataset files name as train-stats.jsonl, test-stats.jsonl. dev-stats.jsonl the command windows start to open and close up infinitely. 
So I hardly take a screenshot of cmd window where it says :
"sh" is not recognized as an internal or external command, 
operable program or batch file.
Well I know windows don't have "sh" command but i can't pinpoint as well where the error is coming from. Please help me out here

**Comment by tshi04** [comment]
I have not tested the codes on windows. Can you try it on Ubuntu?

**Comment by Shanzaay** [comment]
Unfortunately i can't.
