### ISSUE TITLE
tokenize time for dataset

### ISSUE THREAD

**Issue by Shanzaay** [tshi04/AbsSum#9]
Hi, I am using the Bytecup dataset. While I am tokenizing the dataset using tokenize.py. Numbers from 1 to 64 are printed. After that, the file is still executing but nothing else is happening. Nor the execution is stoping. Am I doing something wrong or how long it takes to tokenize the dataset?

**Comment by Shanzaay** [comment]
The new1.txt file that is supposed to be created after executing tokenize.py. What should that file contain? and how long does it takes to tokenize?

**Comment by Shanzaay** [comment]
![bytecup](https://user-images.githubusercontent.com/34294260/71633443-24793200-2c36-11ea-8ade-d87596329aeb.PNG)

This is the output i am getting in my console.

**Comment by tshi04** [comment]
Tokenization may take a couple of hours. Here is a preprocessed data.
https://drive.google.com/open?id=1RknrtkbUIkpilJUFGiHN4Oi85xhnb3vV

**Comment by Shanzaay** [comment]
Thank you for your response.
